// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SpreadsheetGuiTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// populateSpreadsheet - Use 'populateSpreadsheetParams' to pass parameters into this method.
        /// </summary>
        public void populateSpreadsheet()
        {
            #region Variable Declarations
            WinEdit uICContentEdit = this.UISpreadsheet1Window.UICContentWindow.UICContentEdit;
            WinClient uISPanelClient = this.UISpreadsheet1Window.UIItemWindow.UISPanelClient;
            WinWindow uISpreadsheet1Window1 = this.UISpreadsheet1Window;
            WinMenuItem uIEmptySpreadsheetMenuItem = this.UIItemWindow.UIDropDownMenu.UIEmptySpreadsheetMenuItem;
            #endregion

            // Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
            ApplicationUnderTest uISpreadsheet1Window = ApplicationUnderTest.Launch(this.populateSpreadsheetParams.UISpreadsheet1WindowExePath, this.populateSpreadsheetParams.UISpreadsheet1WindowAlternateExePath);

            // Type 'a' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(89, 64));

            // Type 'sfw' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText1;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(59, 90));

            // Type 'wefwe' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText2;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(70, 76));

            // Type 'wefwe' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText3;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(164, 52));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(163, 38));

            // Type 'wfwef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText4;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(157, 136));

            // Type 'wefew' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText5;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(143, 72));

            // Type 'we' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText6;

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(154, 103));

            // Type 'wef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText7;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(157, 118));

            // Type 'we' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText8;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(174, 122));

            // Type 'few' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText9;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(237, 101));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText10;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(233, 76));

            // Type 'wef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText11;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(223, 52));

            // Type 'w' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText12;

            // Type 'e' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys1, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(218, 36));

            // Type 'fwefwe' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText13;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(258, 99));

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys2, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(245, 145));

            // Type 'wef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText14;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(244, 173));

            // Type 'we' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText15;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(433, 156));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText16;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(421, 93));

            // Type 'ew' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText17;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(368, 75));
            Mouse.StopDragging(uISPanelClient, -44, -2);

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText18;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(266, 74));
            Mouse.StopDragging(uISPanelClient, -13, 17);

            // Type 'efff' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText19;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(222, 128));

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(143, 130));
            Mouse.StopDragging(uISPanelClient, -8, -4);

            // Type 'wefew' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText20;

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys3, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(90, 84));

            // Type 'ewf' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys4, ModifierKeys.None);

            // Click 'Spreadsheet 1' window
            Mouse.Click(uISpreadsheet1Window1, new Point(1, 256));

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(11, 179));
            Mouse.StopDragging(uISPanelClient, 11, 6);

            // Type 'fwefwe' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText21;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(121, 162));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(64, 128));

            // Type 'ef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText22;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(63, 113));

            // Type 'e' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText23;

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys5, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(83, 162));

            // Last mouse action was not recorded.

            // Type 'e' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText24;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(88, 162));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText25;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(111, 186));
            Mouse.StopDragging(uISPanelClient, 19, 8);

            // Type 'ef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText26;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(252, 201));

            // Type 'e' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText27;

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys6, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(351, 173));

            // Type 'ef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText28;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(354, 106));

            // Type 'eew' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText29;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(313, 92));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText30;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(284, 118));
            Mouse.StopDragging(uISPanelClient, -1, 7);

            // Type 'ef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText31;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(295, 144));

            // Type 'e' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText32;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(298, 153));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText33;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(284, 175));

            // Type 'ewf' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText34;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(273, 210));

            // Type 'ewf' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText35;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(314, 220));

            // Type 'e' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys7, ModifierKeys.None);

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(424, 203));
            Mouse.StopDragging(uISPanelClient, 22, -2);

            // Type 'w' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText36;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(534, 158));

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys8, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(528, 129));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(492, 124));

            // Type 'dfs' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText37;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(464, 114));

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(428, 100));
            Mouse.StopDragging(uISPanelClient, -8, 0);

            // Type 'w' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys9, ModifierKeys.None);

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(359, 88));
            Mouse.StopDragging(uISPanelClient, -9, 1);

            // Type 'ef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText38;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(320, 120));
            Mouse.StopDragging(uISPanelClient, 3, 14);

            // Type 'wee' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText39;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(321, 140));

            // Type 'fe' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText40;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(307, 48));

            // Type 'e' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText41;

            // Double-Click 'sPanel' client
            Mouse.DoubleClick(uISPanelClient, new Point(310, 34));

            // Type 'fw' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText42;

            // Last mouse action was not recorded.

            // Type 'fwf' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText43;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(211, 113));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(216, 135));

            // Type 'fawef' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText44;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(190, 146));
            Mouse.StopDragging(uISPanelClient, -16, 7);

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText45;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(150, 186));

            // Type 'f' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.populateSpreadsheetParams.UICContentEditSendKeys10, ModifierKeys.None);

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(149, 222));
            Mouse.StopDragging(uISPanelClient, -3, 6);

            // Type 'a' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText46;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(120, 240));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText47;

            // Move 'sPanel' client
            Mouse.StartDragging(uISPanelClient, new Point(92, 219));
            Mouse.StopDragging(uISPanelClient, -6, -19);

            // Type 'af' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText48;

            // Double-Click 'sPanel' client
            Mouse.DoubleClick(uISPanelClient, new Point(75, 162));

            // Type 'f' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText49;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(82, 138));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(367, 45));

            // Type 'adsfasd' in 'cContent' text box
            uICContentEdit.Text = this.populateSpreadsheetParams.UICContentEditText50;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(432, 106));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(71, 41));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(290, 33));

            // Right-Click 'sPanel' client
            Mouse.Click(uISPanelClient, MouseButtons.Right, ModifierKeys.None, new Point(458, 69));

            // Click 'Empty Spreadsheet' menu item
            Mouse.Click(uIEmptySpreadsheetMenuItem, new Point(51, 14));
        }
        
        /// <summary>
        /// clear - Use 'clearExpectedValues' to pass parameters into this method.
        /// </summary>
        public void clear()
        {
            #region Variable Declarations
            WinEdit uICValueEdit = this.UISpreadsheet1Window.UICValueWindow.UICValueEdit;
            #endregion

            // Verify that the 'Text' property of 'cValue' text box equals ''
            Assert.AreEqual(this.clearExpectedValues.UICValueEditText, uICValueEdit.Text, "sp was sucessfully cleared");
        }
        
        /// <summary>
        /// close
        /// </summary>
        public void close()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UISpreadsheet1Window.UISpreadsheet1TitleBar.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(40, 15));
        }
        
        /// <summary>
        /// a1 has a value and b2 has no value
        /// </summary>
        public void add1()
        {
            #region Variable Declarations
            WinEdit uICContentEdit = this.UISpreadsheet1Window.UICContentWindow.UICContentEdit;
            WinClient uISPanelClient = this.UISpreadsheet1Window.UIItemWindow.UISPanelClient;
            #endregion

            // Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
            ApplicationUnderTest uISpreadsheet1Window = ApplicationUnderTest.Launch(this.add1Params.UISpreadsheet1WindowExePath, this.add1Params.UISpreadsheet1WindowAlternateExePath);

            // Type '5' in 'cContent' text box
            uICContentEdit.Text = this.add1Params.UICContentEditText;

            // Type '{Tab}' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.add1Params.UICContentEditSendKeys, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(62, 62));

            // Type '6' in 'cContent' text box
            uICContentEdit.Text = this.add1Params.UICContentEditText1;

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(98, 79));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(144, 30));

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(138, 44));

            // Type '=a1+b2' in 'cContent' text box
            uICContentEdit.Text = this.add1Params.UICContentEditText2;

            // Type '{Enter}' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.add1Params.UICContentEditSendKeys1, ModifierKeys.None);
        }
        
        /// <summary>
        /// a1 = 5, b2 = no value, so a1+b2 = 5
        /// </summary>
        public void add2()
        {
            #region Variable Declarations
            WinEdit uICValueEdit = this.UISpreadsheet1Window.UICValueWindow.UICValueEdit;
            #endregion

            // Verify that the 'Text' property of 'cValue' text box equals '5'
            Assert.AreEqual(this.add2ExpectedValues.UICValueEditText, uICValueEdit.Text, "Should be 5. A1 = 5 b2 = 0, since no value. ");
        }
        
        /// <summary>
        /// updateb2add - Use 'updateb2addParams' to pass parameters into this method.
        /// </summary>
        public void updateb2add()
        {
            #region Variable Declarations
            WinClient uISPanelClient = this.UISpreadsheet1Window.UIItemWindow.UISPanelClient;
            WinEdit uICContentEdit = this.UISpreadsheet1Window.UICContentWindow.UICContentEdit;
            #endregion

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(140, 58));

            // Type '1' in 'cContent' text box
            uICContentEdit.Text = this.updateb2addParams.UICContentEditText;

            // Type '{Enter}' in 'cContent' text box
            Keyboard.SendKeys(uICContentEdit, this.updateb2addParams.UICContentEditSendKeys, ModifierKeys.None);

            // Click 'sPanel' client
            Mouse.Click(uISPanelClient, new Point(120, 44));
        }
        
        /// <summary>
        /// updateadd - Use 'updateaddExpectedValues' to pass parameters into this method.
        /// </summary>
        public void updateadd()
        {
            #region Variable Declarations
            WinEdit uICValueEdit = this.UISpreadsheet1Window.UICValueWindow.UICValueEdit;
            #endregion

            // Verify that the 'Text' property of 'cValue' text box equals '6'
            Assert.AreEqual(this.updateaddExpectedValues.UICValueEditText, uICValueEdit.Text, "a1 = 5 b2 = 1 so b1 =6");
        }
        
        /// <summary>
        /// close1
        /// </summary>
        public void close1()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UISpreadsheet1Window.UISpreadsheet1TitleBar.UICloseButton;
            WinButton uINOButton = this.UIChangesNotSavedWindow.UINOWindow.UINOButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(28, 9));

            // Click '&No' button
            Mouse.Click(uINOButton, new Point(35, 19));
        }
        
        #region Properties
        public virtual populateSpreadsheetParams populateSpreadsheetParams
        {
            get
            {
                if ((this.mpopulateSpreadsheetParams == null))
                {
                    this.mpopulateSpreadsheetParams = new populateSpreadsheetParams();
                }
                return this.mpopulateSpreadsheetParams;
            }
        }
        
        public virtual clearExpectedValues clearExpectedValues
        {
            get
            {
                if ((this.mclearExpectedValues == null))
                {
                    this.mclearExpectedValues = new clearExpectedValues();
                }
                return this.mclearExpectedValues;
            }
        }
        
        public virtual add1Params add1Params
        {
            get
            {
                if ((this.madd1Params == null))
                {
                    this.madd1Params = new add1Params();
                }
                return this.madd1Params;
            }
        }
        
        public virtual add2ExpectedValues add2ExpectedValues
        {
            get
            {
                if ((this.madd2ExpectedValues == null))
                {
                    this.madd2ExpectedValues = new add2ExpectedValues();
                }
                return this.madd2ExpectedValues;
            }
        }
        
        public virtual updateb2addParams updateb2addParams
        {
            get
            {
                if ((this.mupdateb2addParams == null))
                {
                    this.mupdateb2addParams = new updateb2addParams();
                }
                return this.mupdateb2addParams;
            }
        }
        
        public virtual updateaddExpectedValues updateaddExpectedValues
        {
            get
            {
                if ((this.mupdateaddExpectedValues == null))
                {
                    this.mupdateaddExpectedValues = new updateaddExpectedValues();
                }
                return this.mupdateaddExpectedValues;
            }
        }
        
        public UISpreadsheet1Window UISpreadsheet1Window
        {
            get
            {
                if ((this.mUISpreadsheet1Window == null))
                {
                    this.mUISpreadsheet1Window = new UISpreadsheet1Window();
                }
                return this.mUISpreadsheet1Window;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIChangesNotSavedWindow UIChangesNotSavedWindow
        {
            get
            {
                if ((this.mUIChangesNotSavedWindow == null))
                {
                    this.mUIChangesNotSavedWindow = new UIChangesNotSavedWindow();
                }
                return this.mUIChangesNotSavedWindow;
            }
        }
        #endregion
        
        #region Fields
        private populateSpreadsheetParams mpopulateSpreadsheetParams;
        
        private clearExpectedValues mclearExpectedValues;
        
        private add1Params madd1Params;
        
        private add2ExpectedValues madd2ExpectedValues;
        
        private updateb2addParams mupdateb2addParams;
        
        private updateaddExpectedValues mupdateaddExpectedValues;
        
        private UISpreadsheet1Window mUISpreadsheet1Window;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UIChangesNotSavedWindow mUIChangesNotSavedWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'populateSpreadsheet'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class populateSpreadsheetParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheet1WindowExePath = "C:\\Users\\Bharath\\Documents\\Visual Studio 2013\\Projects\\PS6\\SpreadsheetGUI\\bin\\Deb" +
            "ug\\SpreadsheetGUI.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheet1WindowAlternateExePath = "%USERPROFILE%\\Documents\\Visual Studio 2013\\Projects\\PS6\\SpreadsheetGUI\\bin\\Debug\\" +
            "SpreadsheetGUI.exe";
        
        /// <summary>
        /// Type 'a' in 'cContent' text box
        /// </summary>
        public string UICContentEditText = "a";
        
        /// <summary>
        /// Type 'sfw' in 'cContent' text box
        /// </summary>
        public string UICContentEditText1 = "sfw";
        
        /// <summary>
        /// Type 'wefwe' in 'cContent' text box
        /// </summary>
        public string UICContentEditText2 = "wefwe";
        
        /// <summary>
        /// Type 'wefwe' in 'cContent' text box
        /// </summary>
        public string UICContentEditText3 = "wefwe";
        
        /// <summary>
        /// Type 'wfwef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText4 = "wfwef";
        
        /// <summary>
        /// Type 'wefew' in 'cContent' text box
        /// </summary>
        public string UICContentEditText5 = "wefew";
        
        /// <summary>
        /// Type 'we' in 'cContent' text box
        /// </summary>
        public string UICContentEditText6 = "we";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys = "f";
        
        /// <summary>
        /// Type 'wef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText7 = "wef";
        
        /// <summary>
        /// Type 'we' in 'cContent' text box
        /// </summary>
        public string UICContentEditText8 = "we";
        
        /// <summary>
        /// Type 'few' in 'cContent' text box
        /// </summary>
        public string UICContentEditText9 = "few";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText10 = "f";
        
        /// <summary>
        /// Type 'wef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText11 = "wef";
        
        /// <summary>
        /// Type 'w' in 'cContent' text box
        /// </summary>
        public string UICContentEditText12 = "w";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys1 = "e";
        
        /// <summary>
        /// Type 'fwefwe' in 'cContent' text box
        /// </summary>
        public string UICContentEditText13 = "fwefwe";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys2 = "f";
        
        /// <summary>
        /// Type 'wef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText14 = "wef";
        
        /// <summary>
        /// Type 'we' in 'cContent' text box
        /// </summary>
        public string UICContentEditText15 = "we";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText16 = "f";
        
        /// <summary>
        /// Type 'ew' in 'cContent' text box
        /// </summary>
        public string UICContentEditText17 = "ew";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText18 = "f";
        
        /// <summary>
        /// Type 'efff' in 'cContent' text box
        /// </summary>
        public string UICContentEditText19 = "efff";
        
        /// <summary>
        /// Type 'wefew' in 'cContent' text box
        /// </summary>
        public string UICContentEditText20 = "wefew";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys3 = "f";
        
        /// <summary>
        /// Type 'ewf' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys4 = "ewf";
        
        /// <summary>
        /// Type 'fwefwe' in 'cContent' text box
        /// </summary>
        public string UICContentEditText21 = "fwefwe";
        
        /// <summary>
        /// Type 'ef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText22 = "ef";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditText23 = "e";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys5 = "f";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditText24 = "e";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText25 = "f";
        
        /// <summary>
        /// Type 'ef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText26 = "ef";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditText27 = "e";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys6 = "f";
        
        /// <summary>
        /// Type 'ef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText28 = "ef";
        
        /// <summary>
        /// Type 'eew' in 'cContent' text box
        /// </summary>
        public string UICContentEditText29 = "eew";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText30 = "f";
        
        /// <summary>
        /// Type 'ef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText31 = "ef";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditText32 = "e";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText33 = "f";
        
        /// <summary>
        /// Type 'ewf' in 'cContent' text box
        /// </summary>
        public string UICContentEditText34 = "ewf";
        
        /// <summary>
        /// Type 'ewf' in 'cContent' text box
        /// </summary>
        public string UICContentEditText35 = "ewf";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys7 = "e";
        
        /// <summary>
        /// Type 'w' in 'cContent' text box
        /// </summary>
        public string UICContentEditText36 = "w";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys8 = "f";
        
        /// <summary>
        /// Type 'dfs' in 'cContent' text box
        /// </summary>
        public string UICContentEditText37 = "dfs";
        
        /// <summary>
        /// Type 'w' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys9 = "w";
        
        /// <summary>
        /// Type 'ef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText38 = "ef";
        
        /// <summary>
        /// Type 'wee' in 'cContent' text box
        /// </summary>
        public string UICContentEditText39 = "wee";
        
        /// <summary>
        /// Type 'fe' in 'cContent' text box
        /// </summary>
        public string UICContentEditText40 = "fe";
        
        /// <summary>
        /// Type 'e' in 'cContent' text box
        /// </summary>
        public string UICContentEditText41 = "e";
        
        /// <summary>
        /// Type 'fw' in 'cContent' text box
        /// </summary>
        public string UICContentEditText42 = "fw";
        
        /// <summary>
        /// Type 'fwf' in 'cContent' text box
        /// </summary>
        public string UICContentEditText43 = "fwf";
        
        /// <summary>
        /// Type 'fawef' in 'cContent' text box
        /// </summary>
        public string UICContentEditText44 = "fawef";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText45 = "f";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys10 = "f";
        
        /// <summary>
        /// Type 'a' in 'cContent' text box
        /// </summary>
        public string UICContentEditText46 = "a";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText47 = "f";
        
        /// <summary>
        /// Type 'af' in 'cContent' text box
        /// </summary>
        public string UICContentEditText48 = "af";
        
        /// <summary>
        /// Type 'f' in 'cContent' text box
        /// </summary>
        public string UICContentEditText49 = "f";
        
        /// <summary>
        /// Type 'adsfasd' in 'cContent' text box
        /// </summary>
        public string UICContentEditText50 = "adsfasd";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'clear'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class clearExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'cValue' text box equals ''
        /// </summary>
        public string UICValueEditText = "";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'add1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class add1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheet1WindowExePath = "C:\\Users\\Bharath\\Documents\\Visual Studio 2013\\Projects\\PS6\\SpreadsheetGUI\\bin\\Deb" +
            "ug\\SpreadsheetGUI.exe";
        
        /// <summary>
        /// Launch '%USERPROFILE%\Documents\Visual Studio 2013\Projects\PS6\SpreadsheetGUI\bin\Debug\SpreadsheetGUI.exe'
        /// </summary>
        public string UISpreadsheet1WindowAlternateExePath = "%USERPROFILE%\\Documents\\Visual Studio 2013\\Projects\\PS6\\SpreadsheetGUI\\bin\\Debug\\" +
            "SpreadsheetGUI.exe";
        
        /// <summary>
        /// Type '5' in 'cContent' text box
        /// </summary>
        public string UICContentEditText = "5";
        
        /// <summary>
        /// Type '{Tab}' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '6' in 'cContent' text box
        /// </summary>
        public string UICContentEditText1 = "6";
        
        /// <summary>
        /// Type '=a1+b2' in 'cContent' text box
        /// </summary>
        public string UICContentEditText2 = "=a1+b2";
        
        /// <summary>
        /// Type '{Enter}' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys1 = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'add2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class add2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'cValue' text box equals '5'
        /// </summary>
        public string UICValueEditText = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'updateb2add'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class updateb2addParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in 'cContent' text box
        /// </summary>
        public string UICContentEditText = "1";
        
        /// <summary>
        /// Type '{Enter}' in 'cContent' text box
        /// </summary>
        public string UICContentEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'updateadd'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class updateaddExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'cValue' text box equals '6'
        /// </summary>
        public string UICValueEditText = "6";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISpreadsheet1Window : WinWindow
    {
        
        public UISpreadsheet1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Spreadsheet 1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Spreadsheet 1");
            #endregion
        }
        
        #region Properties
        public UICContentWindow UICContentWindow
        {
            get
            {
                if ((this.mUICContentWindow == null))
                {
                    this.mUICContentWindow = new UICContentWindow(this);
                }
                return this.mUICContentWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UICValueWindow UICValueWindow
        {
            get
            {
                if ((this.mUICValueWindow == null))
                {
                    this.mUICValueWindow = new UICValueWindow(this);
                }
                return this.mUICValueWindow;
            }
        }
        
        public UISpreadsheet1TitleBar UISpreadsheet1TitleBar
        {
            get
            {
                if ((this.mUISpreadsheet1TitleBar == null))
                {
                    this.mUISpreadsheet1TitleBar = new UISpreadsheet1TitleBar(this);
                }
                return this.mUISpreadsheet1TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UICContentWindow mUICContentWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UICValueWindow mUICValueWindow;
        
        private UISpreadsheet1TitleBar mUISpreadsheet1TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UICContentWindow : WinWindow
    {
        
        public UICContentWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cContent";
            this.WindowTitles.Add("Spreadsheet 1");
            #endregion
        }
        
        #region Properties
        public WinEdit UICContentEdit
        {
            get
            {
                if ((this.mUICContentEdit == null))
                {
                    this.mUICContentEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICContentEdit.WindowTitles.Add("Spreadsheet 1");
                    #endregion
                }
                return this.mUICContentEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICContentEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Spreadsheet 1");
            #endregion
        }
        
        #region Properties
        public WinClient UISPanelClient
        {
            get
            {
                if ((this.mUISPanelClient == null))
                {
                    this.mUISPanelClient = new WinClient(this);
                    #region Search Criteria
                    this.mUISPanelClient.WindowTitles.Add("Spreadsheet 1");
                    #endregion
                }
                return this.mUISPanelClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUISPanelClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UICValueWindow : WinWindow
    {
        
        public UICValueWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cValue";
            this.WindowTitles.Add("Spreadsheet 1");
            #endregion
        }
        
        #region Properties
        public WinEdit UICValueEdit
        {
            get
            {
                if ((this.mUICValueEdit == null))
                {
                    this.mUICValueEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUICValueEdit.WindowTitles.Add("Spreadsheet 1");
                    #endregion
                }
                return this.mUICValueEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUICValueEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISpreadsheet1TitleBar : WinTitleBar
    {
        
        public UISpreadsheet1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Spreadsheet 1");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Spreadsheet 1");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "DropDown";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            #endregion
        }
        
        #region Properties
        public UIDropDownMenu UIDropDownMenu
        {
            get
            {
                if ((this.mUIDropDownMenu == null))
                {
                    this.mUIDropDownMenu = new UIDropDownMenu(this);
                }
                return this.mUIDropDownMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIDropDownMenu mUIDropDownMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIDropDownMenu : WinMenu
    {
        
        public UIDropDownMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "DropDown";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIEmptySpreadsheetMenuItem
        {
            get
            {
                if ((this.mUIEmptySpreadsheetMenuItem == null))
                {
                    this.mUIEmptySpreadsheetMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIEmptySpreadsheetMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Empty Spreadsheet";
                    #endregion
                }
                return this.mUIEmptySpreadsheetMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIEmptySpreadsheetMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIChangesNotSavedWindow : WinWindow
    {
        
        public UIChangesNotSavedWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Changes Not Saved";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Changes Not Saved");
            #endregion
        }
        
        #region Properties
        public UINOWindow UINOWindow
        {
            get
            {
                if ((this.mUINOWindow == null))
                {
                    this.mUINOWindow = new UINOWindow(this);
                }
                return this.mUINOWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINOWindow mUINOWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UINOWindow : WinWindow
    {
        
        public UINOWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("Changes Not Saved");
            #endregion
        }
        
        #region Properties
        public WinButton UINOButton
        {
            get
            {
                if ((this.mUINOButton == null))
                {
                    this.mUINOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINOButton.SearchProperties[WinButton.PropertyNames.Name] = "No";
                    this.mUINOButton.WindowTitles.Add("Changes Not Saved");
                    #endregion
                }
                return this.mUINOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINOButton;
        #endregion
    }
}
